// @webtoon/psd
// Copyright 2021-present NAVER WEBTOON
// MIT License

export * from "./pkg/webtoon_psd_decoder";

// This value will be generated by vite-plugin-top-level-await
/**
 * Promise that resolves once the WebAssembly module is ready.
 */
export declare let init: Promise<void>;
